### ISSUE TITLE
Hide folder arrows option

### ISSUE THREAD

**Issue by calvo-jp** [jacobwgillespie/vscode-minimal-icons#1]
Hello. Just started using this extension and I really lke the simplicity. Can we get an option to hide folder arrows?

**Comment by jacobwgillespie** [comment]
Hey glad you're enjoying it! I've published a new version of the extension that includes an additional icon theme without the explorer arrows, if you update to v1.1.1 you should be able to switch:

![image](https://user-images.githubusercontent.com/130874/177039939-166841b9-dbba-473b-9e5e-c8bd74773b9c.png)

**Comment by calvo-jp** [comment]
That was quick. Doing it right now. Thanks a lot, man.
